### ISSUE TITLE
Similar to another project

### ISSUE THREAD

**Issue by nueverest** [lsst-sqre/pytravisci#5]
Are you aware of [travispy](https://github.com/menegazzo/travispy)?  It seems like a very similar project.  Is yours going to be different in some way?

**Comment by athornton** [comment]
I looked at travispy, and I wasn't certain that it was actively maintained, and the documentation is lacking (basically, the 'Getting Started' page is all there is).

It was easier for me to implement my own set of methods for the things I need, which is basically for making Cookiecutter-instantiated LSST projects register with Travis CI at creation time.  You'll notice I don't have any actual build methods, for instance, because I don't yet need to trigger builds from my workflow, and that I play pretty fast and loose with the sync semantics, because what I'm doing for my own work is making sure that a sync started, and then polling until the repo I'm interested in is available.

If you want a complete implementation of the Travis CI API, and you can figure out how to make it work, you should probably be using travispy instead.  If you'd rather use this one but need build triggers and stuff, let me know or send a PR, but at the moment, this one does what I need it to and I've got other project priorities, so my time to go back to this will be limited.

**Comment by nueverest** [comment]
Thanks this helps a lot.  I will stick with travispy for now, but I wanted to make sure I wasn't missing something.
